name: Actions Workflow 

on:
  schedule:
    - cron: '* * * * *'
  push:
    branches:
      - main
      - test
jobs:
  test_schedule:
    run-on: [self-hosted]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run some simple commands
        run: |
          pwd
          ls -a
          apt get update


