name: Actions Workflow 
on:
  schedule:
    - cron: '* * * * *'
  push:
  
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello World"
        timeout-minutes: 0
      - name: multiline script 
        run: |
          pwd
          ls -a
          apt get update


