name: Actions Workflow 

on:
  schedule:
    - cron: '* * * * *'
  push:
    branches:
      - main
      - test
jobs:
  test_schedule:
    run-on: self-hosted
    steps:

      - name: run some simple commands
        run: |
          pwd
          ls -a
         


