name: Actions Workflow 

on:
  schedule:
    # Runs every minute
    - cron: '*/5 * * * *'

jobs:
  run-shell-command:
    runs-on: self-hosted
    steps: 
      - name: echo a string
        run: echo "Hello World"
        timeout-minutes: 0
      - name: multiline script 
        run: |
          pwd
          ls -a



